FROM centos:7

RUN curl -Ls https://copr.fedorainfracloud.org/coprs/g/maistra/istio-daily/repo/epel-7/group_openshift-istio-istio-daily-epel-7.repo -o /etc/yum.repos.d/openshift-istio-istio-daily-epel-7.repo && \
    yum upgrade -y && \
    yum install -y istio-mixs && \
    yum clean all

WORKDIR /tmp/

ENTRYPOINT ["/usr/local/bin/mixs", "server"]
CMD ["--configStoreURL=fs:///etc/opt/mixer/configroot","--configStoreURL=k8s://"]
