FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ARG REPO=https://copr.fedorainfracloud.org/coprs/g/maistra/istio-1.2/repo/epel-8/group_maistra-istio-1.2-epel-8.repo
ARG VERSION=2.0.1
ARG ISTIO_VERSION=1.6.14

LABEL com.redhat.component="maistra-mixer-container"
LABEL name="maistra/mixer-ubi8"
LABEL version="${VERSION}"
LABEL istio_version="${ISTIO_VERSION}"
LABEL summary="Red Hat Istio Mixer OpenShift container image"
LABEL description="Red Hat Istio Mixer OpenShift container image"
LABEL io.k8s.display-name="Red Hat Istio Mixer"
LABEL io.openshift.tags="istio"
LABEL maintainer="Istio Feedback <istio-feedback@redhat.com>"
LABEL io.openshift.expose-services=""
ENV container="oci"
ENV ISTIO_VERSION="${ISTIO_VERSION}"

RUN curl -Ls ${REPO} -o /etc/yum.repos.d/maistra.repo && \
    microdnf update -y && \
    microdnf install -y istio-mixs-${VERSION} && \
    microdnf clean all

WORKDIR /tmp/

ENTRYPOINT ["/usr/local/bin/mixs", "server"]
CMD ["--configStoreURL=fs:///etc/opt/mixer/configroot","--configStoreURL=k8s://"]
