FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

LABEL com.redhat.component="maistra-mixer-container"
LABEL name="maistra/mixer-ubi8"
LABEL version="1.0.5"
LABEL istion_version="1.1.17"
LABEL summary="Red Hat Istio Mixer OpenShift container image"
LABEL description="Red Hat Istio Mixer OpenShift container image"
LABEL io.k8s.display-name="Red Hat Istio Mixer"
LABEL io.openshift.tags="istio"
LABEL maintainer="Istio Feedback <istio-feedback@redhat.com>"
LABEL io.openshift.expose-services=""
ENV container="oci"
ENV ISTIO_VERSION=1.1.17

RUN curl -Ls https://copr.fedorainfracloud.org/coprs/g/maistra/istio.el8/repo/epel-8/group_maistra-istio.el8-epel-8.repo -o /etc/yum.repos.d/openshift-istio-istio-epel-8.repo && \
    microdnf update -y && \
    microdnf install -y istio-mixs-1.0.5 && \
    microdnf clean all

WORKDIR /tmp/

ENTRYPOINT ["/usr/local/bin/mixs", "server"]
CMD ["--configStoreURL=fs:///etc/opt/mixer/configroot","--configStoreURL=k8s://"]
