FROM centos:7

RUN yum upgrade -y && \
    yum install -y iptables iproute && \
    yum clean all

WORKDIR /tmp/

ADD artifacts/istio-iptables.sh /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/istio-iptables.sh"]
