FROM centos:7

RUN curl -Ls https://copr.fedorainfracloud.org/coprs/g/maistra/istio/repo/epel-7/group_maistra-istio-epel-7.repo -o /etc/yum.repos.d/maistra-istio-epel-7.repo && \
    yum upgrade -y && \
    yum install -y istio-galley && \
    yum clean all

WORKDIR /tmp/

ENTRYPOINT [ "/usr/local/bin/galley"]
